#!/bin/vbash
# shellcheck shell=bash

set firewall zone guest default-action 'drop'
set firewall zone guest from iot firewall name 'iot-guest'
set firewall zone guest from not firewall name 'not-guest'
set firewall zone guest from lan firewall name 'lan-guest'
set firewall zone guest from local firewall name 'local-guest'
set firewall zone guest from mgmt firewall name 'mgmt-guest'
set firewall zone guest from services firewall name 'services-guest'
set firewall zone guest from primary firewall name 'primary-guest'
set firewall zone guest from data firewall name 'data-guest'
set firewall zone guest from wan firewall name 'wan-guest'
set firewall zone guest interface 'eth3.3'

set firewall zone iot default-action 'drop'
set firewall zone iot from guest firewall name 'guest-iot'
set firewall zone iot from lan firewall name 'lan-iot'
set firewall zone iot from not firewall name 'not-iot'
set firewall zone iot from local firewall name 'local-iot'
set firewall zone iot from mgmt firewall name 'mgmt-iot'
set firewall zone iot from services firewall name 'services-iot'
set firewall zone iot from primary firewall name 'primary-iot'
set firewall zone iot from data firewall name 'data-iot'
set firewall zone iot from wan firewall name 'wan-iot'
set firewall zone iot interface 'eth3.50'

set firewall zone not default-action 'drop'
set firewall zone not from guest firewall name 'guest-not'
set firewall zone not from iot firewall name 'iot-not'
set firewall zone not from lan firewall name 'lan-not'
set firewall zone not from local firewall name 'local-not'
set firewall zone not from mgmt firewall name 'mgmt-not'
set firewall zone not from services firewall name 'services-not'
set firewall zone not from primary firewall name 'primary-not'
set firewall zone not from data firewall name 'data-not'
set firewall zone not from wan firewall name 'wan-not'
set firewall zone not interface 'eth3.60'

set firewall zone lan default-action 'drop'
set firewall zone lan from guest firewall name 'guest-lan'
set firewall zone lan from iot firewall name 'iot-lan'
set firewall zone lan from not firewall name 'not-lan'
set firewall zone lan from local firewall name 'local-lan'
set firewall zone lan from mgmt firewall name 'mgmt-lan'
set firewall zone lan from services firewall name 'services-lan'
set firewall zone lan from primary firewall name 'primary-lan'
set firewall zone lan from data firewall name 'data-lan'
set firewall zone lan from wan firewall name 'wan-lan'
set firewall zone lan interface 'eth3'

set firewall zone local default-action 'drop'
set firewall zone local description 'Local router zone'
set firewall zone local from guest firewall name 'guest-local'
set firewall zone local from iot firewall name 'iot-local'
set firewall zone local from not firewall name 'not-local'
set firewall zone local from lan firewall name 'lan-local'
set firewall zone local from mgmt firewall name 'mgmt-local'
set firewall zone local from services firewall name 'services-local'
set firewall zone local from primary firewall name 'primary-local'
set firewall zone local from data firewall name 'data-local'
set firewall zone local from wan firewall name 'wan-local'
set firewall zone local local-zone

set firewall zone mgmt default-action 'drop'
set firewall zone mgmt from guest firewall name 'guest-mgmt'
set firewall zone mgmt from iot firewall name 'iot-mgmt'
set firewall zone mgmt from not firewall name 'not-mgmt'
set firewall zone mgmt from lan firewall name 'lan-mgmt'
set firewall zone mgmt from local firewall name 'local-mgmt'
set firewall zone mgmt from services firewall name 'services-mgmt'
set firewall zone mgmt from primary firewall name 'primary-mgmt'
set firewall zone mgmt from data firewall name 'data-mgmt'
set firewall zone mgmt from wan firewall name 'wan-mgmt'
set firewall zone mgmt interface 'eth3.9'

set firewall zone services default-action 'drop'
set firewall zone services description 'VyOS services zone'
set firewall zone services from guest firewall name 'guest-services'
set firewall zone services from iot firewall name 'iot-services'
set firewall zone services from not firewall name 'not-services'
set firewall zone services from lan firewall name 'lan-services'
set firewall zone services from local firewall name 'local-services'
set firewall zone services from mgmt firewall name 'mgmt-services'
set firewall zone services from primary firewall name 'primary-services'
set firewall zone services from data firewall name 'data-services'
set firewall zone services from wan firewall name 'wan-services'
set firewall zone services interface 'cni-services'

set firewall zone primary default-action 'drop'
set firewall zone primary from guest firewall name 'guest-primary'
set firewall zone primary from iot firewall name 'iot-primary'
set firewall zone primary from not firewall name 'not-primary'
set firewall zone primary from lan firewall name 'lan-primary'
set firewall zone primary from local firewall name 'local-primary'
set firewall zone primary from mgmt firewall name 'mgmt-primary'
set firewall zone primary from services firewall name 'services-primary'
set firewall zone primary from data firewall name 'data-primary'
set firewall zone primary from wan firewall name 'wan-primary'
set firewall zone primary interface 'eth3.4'

set firewall zone data default-action 'drop'
set firewall zone data from guest firewall name 'guest-data'
set firewall zone data from iot firewall name 'iot-data'
set firewall zone data from not firewall name 'not-data'
set firewall zone data from lan firewall name 'lan-data'
set firewall zone data from local firewall name 'local-data'
set firewall zone data from mgmt firewall name 'mgmt-data'
set firewall zone data from services firewall name 'services-data'
set firewall zone data from primary firewall name 'primary-data'
set firewall zone data from wan firewall name 'wan-data'
set firewall zone data interface 'eth3.11'

set firewall zone wan default-action 'drop'
set firewall zone wan from guest firewall name 'guest-wan'
set firewall zone wan from iot firewall name 'iot-wan'
set firewall zone wan from not firewall name 'not-wan'
set firewall zone wan from lan firewall name 'lan-wan'
set firewall zone wan from local firewall name 'local-wan'
set firewall zone wan from mgmt firewall name 'mgmt-wan'
set firewall zone wan from services firewall name 'services-wan'
set firewall zone wan from primary firewall name 'primary-wan'
set firewall zone wan from data firewall name 'data-wan'
set firewall zone wan interface 'eth0'
